
x-casaos:
  architectures:
    - amd64
  author: Chatin
  category: Network
  description:
  en_us: Web application firewall (WAF) and reverse proxy (remark that first startup time minimum 10 minutes)
  custom: Web application firewall (WAF) and reverse proxy (remark that first startup time minimum 10 minutes)
  hostname: ""
  icon: https://github.com/chaitin/SafeLine/blob/main/images/banner.png
  index: /
  is_uncontrolled: false
  port_map: "9443"
  scheme: http
  title:
    en_us: Safeline
    custom: Safeline

networks:
  safeline-ce:
    name: safeline-ce
    driver: bridge
    ipam:
      driver: default
      config:
        - gateway: 172.22.222.1
          subnet: 172.22.222.0/24
    driver_opts:
      com.docker.network.bridge.name: safeline-ce
    environment:
      # Common
      - SAFELINE_DIR=/DATA/AppData/safeline
      - IMAGE_TAG=latest
      - MGT_PORT=9443
      - POSTGRES_PASSWORD={postgres-password}
      - SUBNET_PREFIX=172.22.222
      - IMAGE_PREFIX=chaitin
      - ARCH_SUFFIX=
      - RELEASE=
      - REGION=-g

services:
  postgres:
    container_name: safeline-pg
    restart: always
    image: chaitin/safeline-postgres:15.2
    volumes:
      - /DATA/AppData/safeline/resources/postgres/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=safeline-ce
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?postgres password required}
      # Common
      - SAFELINE_DIR=/DATA/AppData/safeline
      - IMAGE_TAG=latest
      - MGT_PORT=9443
      - POSTGRES_PASSWORD={postgres-password}
      - SUBNET_PREFIX=172.22.222
      - IMAGE_PREFIX=chaitin
      - ARCH_SUFFIX=
      - RELEASE=
      - REGION=-g
    networks:
      safeline-ce:
        ipv4_address: 172.22.222.2
    command: [postgres, -c, max_connections=600]
    healthcheck:
      test: pg_isready -U safeline-ce -d safeline-ce

  mgt:
    container_name: safeline-mgt
    restart: always
    image: chaitin/safeline-mgt-g:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /DATA/AppData/safeline/resources/mgt:/app/data
      - /DATA/AppData/safeline/logs/nginx:/app/log/nginx:z
      - /DATA/AppData/safeline/resources/sock:/app/sock
      - /var/run:/app/run
    ports:
      - "9443:1443"
    healthcheck:
      test: curl -k -f https://localhost:1443/api/open/health
    environment:
      - MGT_PG=postgres://safeline-ce:${POSTGRES_PASSWORD}@safeline-pg/safeline-ce?sslmode=disable
      # Common
      - SAFELINE_DIR=/DATA/AppData/safeline
      - IMAGE_TAG=latest
      - MGT_PORT=9443
      - POSTGRES_PASSWORD={postgres-password}
      - SUBNET_PREFIX=172.22.222
      - IMAGE_PREFIX=chaitin
      - ARCH_SUFFIX=
      - RELEASE=
      - REGION=-g
    depends_on:
      - postgres
      - fvm
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    networks:
      safeline-ce:
        ipv4_address: 172.22.222.4

  detect:
    container_name: safeline-detector
    restart: always
    image: chaitin/safeline-detector-g:latest
    volumes:
      - /DATA/AppData/safeline/resources/detector:/resources/detector
      - /DATA/AppData/safeline/logs/detector:/logs/detector
      - /etc/localtime:/etc/localtime:ro
    environment:
      - LOG_DIR=/logs/detector
      # Common
      - SAFELINE_DIR=/DATA/AppData/safeline
      - IMAGE_TAG=latest
      - MGT_PORT=9443
      - POSTGRES_PASSWORD={postgres-password}
      - SUBNET_PREFIX=172.22.222
      - IMAGE_PREFIX=chaitin
      - ARCH_SUFFIX=
      - RELEASE=
      - REGION=-g
    networks:
      safeline-ce:
        ipv4_address: 172.22.222.5

  tengine:
    container_name: safeline-tengine
    restart: always
    image: chaitin/safeline-tengine-g:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/resolv.conf:/etc/resolv.conf:ro
      - /DATA/AppData/safeline/resources/nginx:/etc/nginx
      - /DATA/AppData/safeline/resources/detector:/resources/detector
      - /DATA/AppData/safeline/resources/chaos:/resources/chaos
      - /DATA/AppData/safeline/logs/nginx:/var/log/nginx:z
      - /DATA/AppData/safeline/resources/cache:/usr/local/nginx/cache
      - /DATA/AppData/safeline/resources/sock:/app/sock
    environment:
      - TCD_MGT_API=https://172.22.222.4:1443/api/open/publish/server
      - TCD_SNSERVER=172.22.222.5:8000
      # deprecated
      - SNSERVER_ADDR=172.22.222.5:8000
      - CHAOS_ADDR=172.22.222.10
      # Common
      - SAFELINE_DIR=/DATA/AppData/safeline
      - IMAGE_TAG=latest
      - MGT_PORT=9443
      - POSTGRES_PASSWORD={postgres-password}
      - SUBNET_PREFIX=172.22.222
      - IMAGE_PREFIX=chaitin
      - ARCH_SUFFIX=
      - RELEASE=
      - REGION=-g
    ulimits:
      nofile: 131072
    network_mode: host

  luigi:
    container_name: safeline-luigi
    restart: always
    image: chaitin/safeline-luigi-g:latest
    environment:
      - MGT_IP=172.22.222.4
      - LUIGI_PG=postgres://safeline-ce:${POSTGRES_PASSWORD}@safeline-pg/safeline-ce?sslmode=disable
      # Common
      - SAFELINE_DIR=/DATA/AppData/safeline
      - IMAGE_TAG=latest
      - MGT_PORT=9443
      - POSTGRES_PASSWORD={postgres-password}
      - SUBNET_PREFIX=172.22.222
      - IMAGE_PREFIX=chaitin
      - ARCH_SUFFIX=
      - RELEASE=
      - REGION=-g
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /DATA/AppData/safeline/resources/luigi:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    depends_on:
      - detect
      - mgt
    networks:
      safeline-ce:
        ipv4_address: 172.22.222.7

  fvm:
    container_name: safeline-fvm
    restart: always
    image: chaitin/safeline-fvm-g:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    environment:
      # Common
      - SAFELINE_DIR=/DATA/AppData/safeline
      - IMAGE_TAG=latest
      - MGT_PORT=9443
      - POSTGRES_PASSWORD={postgres-password}
      - SUBNET_PREFIX=172.22.222
      - IMAGE_PREFIX=chaitin
      - ARCH_SUFFIX=
      - RELEASE=
      - REGION=-g
    networks:
      safeline-ce:
        ipv4_address: 172.22.222.8

  chaos:
    container_name: safeline-chaos
    restart: always
    image: chaitin/safeline-chaos-g:latest
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    environment:
      - DB_ADDR=postgres://safeline-ce:${POSTGRES_PASSWORD}@safeline-pg/safeline-ce?sslmode=disable
      # Common
      - SAFELINE_DIR=/DATA/AppData/safeline
      - IMAGE_TAG=latest
      - MGT_PORT=9443
      - POSTGRES_PASSWORD={postgres-password}
      - SUBNET_PREFIX=172.22.222
      - IMAGE_PREFIX=chaitin
      - ARCH_SUFFIX=
      - RELEASE=
      - REGION=-g
    volumes:
      - /DATA/AppData/safeline/resources/sock:/app/sock
      - /DATA/AppData/safeline/resources/chaos:/app/chaos
    networks:
      safeline-ce:
        ipv4_address: 172.22.222.10
